# Gate thresholds (aligned with decision flow) and lead-time conservatism
gate:
  go: { hs_m: 1.00, wind_kt: 20.0 }
  conditional: { hs_m: 1.20, wind_kt: 22.0 }
leadtime_adjust:
  d4: { hs_m: 0.10, wind_kt: -1.0 }
  d5: { hs_m: 0.10, wind_kt: -1.0 }
  d6: { hs_m: 0.20, wind_kt: -2.0 }
  d7: { hs_m: 0.20, wind_kt: -2.0 }
