name: ML Retraining

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train long-range model
        run: |
          python scripts/train_ml_model.py --output artifacts/ml --metadata artifacts/ml/metadata.json

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: marine-ml-forecast
          path: artifacts/ml
